stages:
  - build
build:
  stage: build
  image: docker:latest
  script:
    - docker login 172.16.2.9:5005 -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
    - echo ${CI_PIPELINE_ID}
    - docker build -t app/web:${CI_PIPELINE_ID} ./docker/web
    - docker start app/web:${CI_PIPELINE_ID}
